# Generated by Django 5.2.14 on 2026-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("users", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="Asia/Kathmandu", max_length=64),
        ),
    ]
