# Generated by Django 5.2.14 on 2026-07-20 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0002_simplify_activity_models"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="priority",
            new_name="weight",
        ),
    ]
