# Generated by Django 5.2.14 on 2026-05-27 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_session_log_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["-local_date", "-start"]},
        ),
        migrations.RenameIndex(
            model_name="session",
            new_name="tracking_se_user_id_4113f0_idx",
            old_name="tracking_se_user_id_e5cd7c_idx",
        ),
        migrations.RenameIndex(
            model_name="session",
            new_name="tracking_se_user_id_8231c8_idx",
            old_name="tracking_se_user_id_local_date_idx",
        ),
        migrations.RenameIndex(
            model_name="session",
            new_name="tracking_se_created_050c76_idx",
            old_name="tracking_se_created_87f7e2_idx",
        ),
    ]
